version: '3.1'
services:

  drupal:
    image: drupal:9
    ports:
      - 8082:80
    volumes:
      - /home/stagiaire/drupal/ajc-formation-drupal/themes:/var/www/html/themes
      - /home/stagiaire/drupal/ajc-formation-drupal/modules:/var/www/html/modules
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: drupal
    restart: always
